### ISSUE TITLE
Logging data persistence

### ISSUE THREAD

**Issue by jfernandezsqs** [Fraunhofer-AISEC/ids-clearing-house-service#15]
Looking at the Clearing House documentation there is no information about the data transaction storage persistance.
I have search in the different files and I have not find information.
Is it explained or detailed somewhere?
Thanks in advance

**Comment by kragall** [comment]
Sorry, I'm not sure if I understand the question correctly. The Clearing House depends on mongodb docker containers to store persistent data. So the persistence of the data depends on your configuration of the mongodb docker containers. If you did not configure volumes there the data will not be stored persistently on the host. Please check the documentation of the [mongodb docker image](https://hub.docker.com/_/mongo)

**Comment by jfernandezsqs** [comment]
Thank you for the prompt response, I have reviewed the documentation provided.
The point is that we have a requirement that refers to the time that transactions are stored securely in the Clearing House, so that a connector can access them at any time during six months.
I understand that the volumes should be defined in the docker-compose.yml file of the Clearing House. Am I right?

**Comment by jfernandezsqs** [comment]
The documentation provided in this issue for mongodb [mongo](https://hub.docker.com/_/mongo) and the official documentation available for the component have been revised. 
It is not specified in the component documentation how to set these volumes for mongo so that they are persistent. That is, performing a `docker-compose down` does not delete the transactions of the connectors made previously. 

Do you plan to include in the documentation the necessary steps to follow in order to configure the volumes so that they are persistent?

**Comment by kragall** [comment]
We'll check if we can include an example of a mongodb docker configuration with volumes.

However, please note that the configuration examples will not include a `production-ready` configuration. This depends on various factors of the production environment and this information is best covered by the [mongodb documentation](https://docs.mongodb.com/manual/administration/production-notes/) as it includes various important topics that are out-of-scope for the documentation of the Clearing House.

**Comment by jfernandezsqs** [comment]
Could you reopen this issue?
So that when documentation is update we can check the proposed solution.

**Comment by kragall** [comment]
Documentation has been updated. Can you check if this is sufficient for you?
