### ISSUE TITLE
./clearing-house-app/clearing-house-api moved or replaced?

### ISSUE THREAD

**Issue by albertoberreteaga** [Fraunhofer-AISEC/ids-clearing-house-service#20]
Hi,
A previous version of the CH had ./clearing-house-app/clearing-house-api (and ./clearing-house-app/ch-lib/ too) with a Cargo.toml file to config.
I imagine the resources have been organised inside the new structure.
Is there please a direct map of the old resources to the new ones? or the functionality it's all new?
I have a previous version running and any hint to migrate from it to this new one will be really welcome.
Thank you so much in advance.

**Comment by kragall** [comment]
Hi Alberto,

yes, for the new version 0.8.0 there's been quite some reorganization in the source files. I haven't tested a full migration from a previous version, but I believe it should be relatively easy:
- You might want to build new docker images for logging-service, document-api and keyring-api using the docker files [here](https://github.com/Fraunhofer-AISEC/ids-clearing-house-service/tree/master/docker). Most likely using the multistage files. For document-api and keyring-api this might not even be necessary, depending on the version you are migrating from. But for a clean setup it's best to use the same version of all services.
- The old `clearing-house-api` is basically the new `logging-service`. You might just rename the service in docker-compose and make sure that it has access to the mongodb you used before. Again, depending on the version you are migrating from there might not even be a difference in the functionality.

**Comment by albertoberreteaga** [comment]
Hi!

Thank you so much here too! 😊

I will test this asap.

BR,

Alberto
