### ISSUE TITLE
error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by juerware** [Fraunhofer-AISEC/ids-clearing-house-service#32]
I will try to do my best in orden to explain the problem.

The problem is the same for "Logging Service", "Document API" and "Keyring API"

If I follow the following documentation:
https://github.com/Fraunhofer-AISEC/ids-clearing-house-service/tree/master/clearing-house-app#logging-service

There is a point in which the following command has to exectute:
`cargo build --release`

Therefore, the binary files are created for the 3 services, the problem is that these binaries are compiled according ssl version in the machine that is compiled, in these case ubuntu 22.04 with openssl 3

but when images are created according to documentation with files document-api.Dockerfile, keyring-api.Dockerfile and logging-service.Dockerfile, these dockerfiles use `FROM ubuntu:20.04` and these version of ubuntu uses openssl 1

Therefore libssl.so.3 is not found because ubuntu 20.04 has libssl1.1 by default.

**Comment by kragall** [comment]
I upgraded the docker files to use ubuntu 22.04 and hope that this fixes your issue.
